version: '3.4'

services:
  postgres-server:
    ports:
     - '5432:5432' 
    image: postgres:15.1
    container_name: postgresql
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: OlympusHealth
      POSTGRES_USER: 'postgres'
    networks:
      - olympus-health

  client:
    image: client
    build:
        context: ./client
        dockerfile: Dockerfile
    networks:
      - olympus-health  
  backend:
    image: ${DOCKER_REGISTRY-}backend
    build:
      context: .
      dockerfile: Backend/Dockerfile
    networks:
        - olympus-health

  
  #proxy:
  #  image: nginx:mainline
  #  networks:
  #    - olympus-health

networks:
  olympus-health:
    driver: bridge